---
output:
  pdf_document:
    highlight: default
    keep_tex: no
    number_sections: yes
    citation_package: natbib  # comentado usa: pandoc-citeproc
    template: latex/plantilla_mma.tex
    pandoc_args: ["--metadata-file=cabecera_capitulos.yaml"]
---

`r xfun::file_string('cabecera_capitulos.tex')`

<!--
```{r include=FALSE}
source("cabecera_chunk_inicio.R")
```
-->

```{r echo=FALSE}
if(!require(pacman)){install.packages("pacman"); library(pacman)}
pacman::p_load("tidyverse", "knitr", "leaps","tidyr","vctrs",
               "exams","leaps","MASS","rsm","car","magrittr")

options(kableExtra.latex.load_packages = F)
knitr::opts_chunk$set(fig.path = 'figurasR/',
                      echo = TRUE, warning = FALSE, message = FALSE,
                      comment = NA,
                      fig.pos="H",fig.align="center",out.width="95%",
                      cache=FALSE) #

knitr::write_bib(c(.packages(),"knitr","rmarkdown"),
                 file="bib/paquetes.bib", width = 60)

#######################################
#exams::include_supplement("myQQnorm.R")
#source("myQQnorm.R")
```


# Nombre del Capítulo 

Puede visitar la página [\textcolor{blue}{Pedro Luis Luque Calvo}](http://destio.us.es/calvo/),  la cual continene material sobre uso del Rmardown para escrituras de documentos y demás temas relacionados con R, Latex, Python, etc. ver. \cite{Luque2017}.

## Primera sección 

El marco \cite{libro1} ..... 


